### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference (github.com/emersion/go-imap/client.(*Client).Login)

### ISSUE THREAD

**Issue by atc0005** [atc0005/check-mail#190]
Found this in a Nagios report to one of our Teams channels:

```
CRITICAL: plugin crash detected. See details via web UI or run plugin manually via CLI.

ERRORS

* plugin crash/panic detected: runtime error: invalid memory address or nil pointer dereference

THRESHOLDS

* Not specified

DETAILED INFO

pre
runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
github.com/atc0005/go-nagios.(*ExitState).ReturnCheckResults(0xc00005c360)
github.com/atc0005/go-nagios@v0.6.0/nagios.go:148 +0xa6f
panic(0x65c900, 0x810710)
runtime/panic.go:971 +0x499
github.com/emersion/go-imap/client.(*Client).State(0x0, 0xc0000280e0)
github.com/emersion/go-imap@v1.1.0/client/client.go:298 +0x2d
github.com/emersion/go-imap/client.(*Client).Login(0x0, 0x7ffd1d14c504, 0x12, 0x7ffd1d14c521, 0xf, 0xc000112480, 0x0)
github.com/emersion/go-imap@v1.1.0/client/cmd_noa
/pre
```

The stack trace is truncated, so I can't see exactly where the problem originated. Will have to handle that separately.

This may affect both binaries, but for now I can only say that it was observed with the Nagios plugin.

**Comment by atc0005** [comment]
> The stack trace is truncated, so I can't see exactly where the problem originated. Will have to handle that separately.

The `atc0005/go-nagios` package has been updated to expose the full stack trace. Once a new build is deployed using that updated library I should have more to go off of when this error occurs again.

**Comment by atc0005** [comment]
Looking back, I found that the panic was recorded twice:

- 2021-07-08 7:12 am (SW channel)
- 2021-07-14 1:15 AM (Alerts channel)

No further occurrences since.

**Comment by atc0005** [comment]
The panic occurred again yesterday for two accounts.

- 2:42:01 pm
- 2:42:03 pm

Captured stack traces:

```log
runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
runtime/debug.Stack(0x6aa878, 0x51, 0xc0000d7278)
runtime/debug/stack.go:24 +0x9f
github.com/atc0005/go-nagios.(*ExitState).ReturnCheckResults(0xc00005a360)
github.com/atc0005/go-nagios@v0.6.1/nagios.go:145 +0xa25
panic(0x65c900, 0x810750)
runtime/panic.go:971 +0x499
github.com/emersion/go-imap/client.(*Client).State(0x0, 0xc000016480)
github.com/emersion/go-imap@v1.1.0/client/client.go:298 +0x2d
github.com/emersion/go-imap/client.(*Client).Login(0x0, 0x7ffc8dbfc6a5, 0x11, 0x7ffc8dbfc6c1, 0x8, 0xc000110480, 0x0)
github.com/emersion/go-imap@v1.1.0/client/cmd_noauth.go:141 +0x2f
github.com/atc0005/check-mail/internal/mbxs.Login(0x0, 0x7ffc8dbfc6a5, 0x11, 0x7ffc8dbfc6c1, 0x8, 0x6e8378, 0xc00002a950, 0xff, 0x0, 0x0, ...)
github.com/atc0005/check-mail/internal/mbxs/connect.go:179 +0x98
main.main()
github.com/atc0005/check-mail/cmd/check_imap_mailbox/main.go:88 +0x7b8
```

```log
runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
runtime/debug.Stack(0x6aa878, 0x51, 0xc0000db278)
runtime/debug/stack.go:24 +0x9f
github.com/atc0005/go-nagios.(*ExitState).ReturnCheckResults(0xc00005a360)
github.com/atc0005/go-nagios@v0.6.1/nagios.go:145 +0xa25
panic(0x65c900, 0x810750)
runtime/panic.go:971 +0x499
github.com/emersion/go-imap/client.(*Client).State(0x0, 0xc000016480)
github.com/emersion/go-imap@v1.1.0/client/client.go:298 +0x2d
github.com/emersion/go-imap/client.(*Client).Login(0x0, 0x7ffc4e7e069f, 0x12, 0x7ffc4e7e06bc, 0x8, 0xc000110480, 0x0)
github.com/emersion/go-imap@v1.1.0/client/cmd_noauth.go:141 +0x2f
github.com/atc0005/check-mail/internal/mbxs.Login(0x0, 0x7ffc4e7e069f, 0x12, 0x7ffc4e7e06bc, 0x8, 0x6e8378, 0xc00002a950, 0xff, 0x0, 0x0, ...)
github.com/atc0005/check-mail/internal/mbxs/connect.go:179 +0x98
main.main()
github.com/atc0005/check-mail/cmd/check_imap_mailbox/main.go:88 +0x7b8
```

**Comment by atc0005** [comment]
The problem appears to ultimately be from declaring `c` as a pointer here:

https://github.com/atc0005/check-mail/blob/e61cfaa70716154840c6737e1eb0606cecb8d857/internal/mbxs/connect.go#L98

and returning `c` here without guaranteeing that it is non-nil:

https://github.com/atc0005/check-mail/blob/e61cfaa70716154840c6737e1eb0606cecb8d857/internal/mbxs/connect.go#L170

The assumption is made that when we loop over the addresses from the DNS lookup here (without checking the length of the `addrs` slice) that we're processing a non-zero length list of addresses:

https://github.com/atc0005/check-mail/blob/e61cfaa70716154840c6737e1eb0606cecb8d857/internal/mbxs/connect.go#L108

We rely on `c` to be properly set here:

https://github.com/atc0005/check-mail/blob/e61cfaa70716154840c6737e1eb0606cecb8d857/internal/mbxs/connect.go#L120

but that isn't reached if the list of IP Addresses is empty, leaving an opportunity for `c` to be nil, which causes issues later.

Another issues is here:

https://github.com/atc0005/check-mail/blob/e61cfaa70716154840c6737e1eb0606cecb8d857/internal/mbxs/connect.go#L176

We receive a pointer to `client.Client`, but don't assert that it's non-nil (early exit). That will need to be updated too.
